# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lego-core}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mathias Stjernstr\303\266m", "Patrik Hedman"]
  s.date = %q{2010-01-12}
  s.description = %q{lego-core the dumb ruby webframework}
  s.email = %q{mathias@globalinn.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/config.ru",
     "lego-core.gemspec",
     "lib/lego.rb",
     "lib/lego/controller.rb",
     "lib/lego/controller/action_context.rb",
     "lib/lego/controller/config.rb",
     "lib/lego/controller/route_handler.rb",
     "lib/lego/plugin.rb",
     "lib/lego/plugin/controller/not_found.rb",
     "spec/integration/test_full_stack_spec.rb",
     "spec/lego/controller/action_context_spec.rb",
     "spec/lego/controller/config_spec.rb",
     "spec/lego/controller/route_handler_spec.rb",
     "spec/lego/controller_spec.rb",
     "spec/lego/plugin/controller/not_found_spec.rb",
     "spec/lego/plugin_spec.rb",
     "spec/lego_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/stjernstrom/lego-core}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{lego-core the dumb ruby webframework}
  s.test_files = [
    "spec/integration/test_full_stack_spec.rb",
     "spec/lego/controller/action_context_spec.rb",
     "spec/lego/controller/config_spec.rb",
     "spec/lego/controller/route_handler_spec.rb",
     "spec/lego/controller_spec.rb",
     "spec/lego/plugin/controller/not_found_spec.rb",
     "spec/lego/plugin_spec.rb",
     "spec/lego_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

